---
abstract: "Apigee.com 'Edge' management API."
author:
  - 'Binary.com <fayland@binary.com>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apigee-Edge
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Mojo::UserAgent: 0
  URI::Escape: 0
resources:
  bugtracker: https://github.com/binary-com/perl-Apigee-Edge/issues
  homepage: https://github.com/binary-com/perl-Apigee-Edge
  repository: https://github.com/binary-com/perl-Apigee-Edge.git
version: 0.03
x_contributors:
  - 'Jean-Yves Sireau <jy@binary.com>'
